spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.131:3306/auth_cloud?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: lian.wei
    password: lian.wei
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 192.168.188.131
    port: 6379
    password: lian.wei
    timeout: 5000
    jedis:
      pool:
        max-active: 10000
        max-idle: 50
        max-wait: -1
        min-idle: 0

server:
  port: 9002
  servlet:
    context-path: /uaa

eureka:
  client:
    service-url:
      defaultZone: http://192.168.188.131:9000/eureka/
    #配置Swagger相关信息
    instance:
      prefer-ip-address: true
      instanceId: ${spring.cloud.client.ipAddress}:${server.port}
      status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

security:
  oauth2:
    resource:
      filter-order: 3
# basic:
#   enabled: false

